version: '3.9'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_DATABASE: messaging_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_DB: messaging_db
      MYSQL_HOST: db

volumes:
  db_data:
